[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

[profile.default]
solc = '0.8.19'
evm_version = 'paris'
src = 'solidity'
test = 'solidity/test'
out = 'out'
libs = ['lib']
fuzz_runs = 2000
optimizer_runs = 10_000
gas_limit = 30_000_000

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 2000

[profile.docs]
src ='solidity/interfaces' # root_path variable in build-docs.sh

[rpc_endpoints]
mainnet = "${ETHEREUM_MAINNET_RPC}"
